### ISSUE TITLE
Sync the Babel vesion used by babel-merge with that used by compile-loader

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino-dev#1024]
babel-merge v2 now has Babel as a dependency. Similar to Neutrino, it pins to an exact version of pre-release Babel 7, since there could still be breaking changes before the final Babel 7 release.

However currently it's pinned to a different (older) version of Babel 7, meaning that two different versions of babel are installed and used side by side in Neutrino.

I'm filing this issue to remind us to sync the versions before Neutrino 9 final is released.

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/babel-merge/pull/9

**Comment by edmorley** [comment]
I misread the babel-merge PR -- it's not using an exact version of Babel 7 pre-release, but a tilde range, so there is no duplication and we can close this out now. Renovate being enabled on that repo will still help keep it up to date however, so handy regardless.
